# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e78773ca8e563bf6b245d606261959b944a30225b61048a7985e7487e72330feb91e6d28ef26dda524ede0d2463facc5bff88301f8db834e8a7184072b4d6a9

test:
  secret_key_base: 19be169cfe990f8553a1b45a53cbf7e6098cf9ff7554789d078f514df90de2e213b6a9d024248ae9a9613595ff9e9a30aa65a8edbade9e9d86c43821d51c93e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
